name: Django-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.2]
      max-parallel: 4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: |
          python manage.py migrate  # Appliquer les migrations

      - name: Run tests and generate report
        run: |
          pytest tests.py --html=report.html  # Exécuter les tests avec pytest et générer un rapport HTML
      
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html  # Télécharger le rapport HTML généré